### ISSUE TITLE
Says attribute "gender" has invalid format

### ISSUE THREAD

**Issue by aarxa** [adrianhajdin/healthcare#13]
I keep facing this error, can someone help? I checked the index.ts file and the CustomFormField and it all looks great.

<img width="1004" alt="Screenshot 2024-07-10 at 4 06 32 AM" src="https://github.com/adrianhajdin/healthcare/assets/113505509/825ba4f8-47d3-4738-aadc-858e6c7afe78">

**Comment by ashdib** [comment]
i think the problem at the contants>index.ts.
I do this
export type Gender = "Male" | "Female" | "Other";

**Comment by aarxa** [comment]
> i think the problem at the contants>index.ts. I do this export type Gender = "Male" | "Female" | "Other";

I tried that but if I assign it as a type how can I use it as a value in RegisterForm.tsx

**Comment by Nkharangra** [comment]
use gender: string instead of gender: Gender in index.d.ts file. this will fix the issue

**Comment by Nkharangra** [comment]
try using this gender: Gender | undefined;

**Comment by FinzyPHINZY** [comment]
I'm having the same issue. @aarxa  how did you resolve it?

**Comment by FinzyPHINZY** [comment]
For anyone who might be facing this issue later, the problem is coming from the appwrite db. the enums value in the gender attributes were registered as 'male','female','other'. so you can change that to "Male"... on appwrite or just change the enum value in the validation.ts and the genderOptions in the /constants/index.ts to "male"...
